### PR TITLE
Added mechanical improvements to game

### PR DESCRIPTION
**Pull request by LambNNot**
Pieces now snap to platforms, pieces can no longer highlight multiple platforms. pieces now turn red when placed into an incorrect platform

### CODE REVIEW

**Comment by jsseng** [comment]
It works, but I am getting conflicts with the main branch.

**Comment by LambNNot** [comment]
I have just resolved the conflicts

**Comment by LambNNot** [comment]
I can go over my refactoring during the meeting or a separate time if you would like to understand the thought process more thoroughly.

**Comment by jsseng** [comment]
Yeah, let's do a separate meeting.

**Comment by LambNNot** [comment]
When/how would you like to schedule it?

**Pull request merged**
